[package]
name = "bench_encodings"
version = "0.1.0"
authors = ["Johann Tuffe <tafia973@gmail.com>"]

[features]
simd-accel = ["encoding_rs/simd-accel"]

[dependencies]
encoding = "0.2.33"
encoding_rs = "0.5.0"
